#############################################################
# KRaft Kafka Cluster                                       #
# L4 Kafka Proxy for Clients                                #
#############################################################
---
version: '2.4'
services:
  #############################################################
  # Kafka CLI                                                 #
  #############################################################
  kafka-cli:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    hostname: kafka-cli
    networks:
      - public
    entrypoint: /bin/bash
    tty: true

  kafkacat:
    image: confluentinc/cp-kafkacat:6.2.0
    hostname: kafkacat
    networks:
      - public
    entrypoint: /bin/bash
    tty: true

  #############################################################
  # Envoy Proxy                                               #
  #############################################################
  envoy-kafka-broker1:
    image: envoyproxy/envoy:${ENVOY_VERSION}
    restart: always
    hostname: envoy-kafka-broker1
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--component-log-level", "kafka:trace"]
    volumes:
      - ./envoy-kafka-broker1.yaml:/etc/envoy/envoy.yaml
    expose:
      - 9092
      - 10000
    networks:
      public:
        aliases:
          - kafka
          - envoy-kafka
      intern: {}

  envoy-kafka-broker2:
    image: envoyproxy/envoy:${ENVOY_VERSION}
    restart: always
    hostname: envoy-kafka-broker2
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--component-log-level", "kafka:trace"]
    expose:
      - 9092
      - 10000
    volumes:
      - ./envoy-kafka-broker2.yaml:/etc/envoy/envoy.yaml
    networks:
      public:
        aliases:
          - kafka
          - envoy-kafka
      intern: {}

  envoy-kafka-broker3:
    image: envoyproxy/envoy:${ENVOY_VERSION}
    restart: always
    hostname: envoy-kafka-broker3
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--component-log-level", "kafka:trace"]
    volumes:
      - ./envoy-kafka-broker3.yaml:/etc/envoy/envoy.yaml
    expose:
      - 9092
      - 10000
    networks:
      public:
        aliases:
          - kafka
          - envoy-kafka
      intern: {}

  #############################################################
  # Kafka Controller                                          #
  #############################################################
  kafka-controller1:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-controller1
    networks:
      - intern
    volumes:
      - kafka-controller1:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: controller # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 1 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PLAINTEXT://:9093 # (by default derived from advertised listeners) List of URIs we will listen on and the listener names. In this case, Kafka listens in both ports on all interfaces.
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT # (required in KRaft mode) A comma-separated list of the names of the listeners used by the controller.

  kafka-controller2:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-controller2
    networks:
      - intern
    volumes:
      - kafka-controller2:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: controller # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 2 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PLAINTEXT://:9093 # (by default derived from advertised listeners) List of URIs we will listen on and the listener names. In this case, Kafka listens in both ports on all interfaces.
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT # (required in KRaft mode) A comma-separated list of the names of the listeners used by the controller.

  kafka-controller3:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-controller3
    networks:
      - intern
    volumes:
      - kafka-controller3:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: controller # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 3 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PLAINTEXT://:9093 # (by default derived from advertised listeners) List of URIs we will listen on and the listener names. In this case, Kafka listens in both ports on all interfaces.
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT # (required in KRaft mode) A comma-separated list of the names of the listeners used by the controller.

  #############################################################
  # Kafka Broker                                              #
  #############################################################
  kafka-broker1:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-broker1
    networks:
      intern:
        aliases:
          - kafka
    volumes:
      - kafka-broker1:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: broker # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 101 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PUBLIC://0.0.0.0:19092,INTERN://0.0.0.0:9092,REPLICATION://0.0.0.0:9091,CONTROLPANE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PUBLIC://envoy-kafka-broker1:9092,INTERN://kafka-broker1:9092,REPLICATION://kafka-broker1:9091,CONTROLPANE://kafka-broker1:9094 # (required) Describes how the host name that is advertised and can be reached by clients. HOST://localhost:19092 enables access from Docker host.
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLPANE
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # (required in KRaft mode) The listeners used by the controller to define the security protocol.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PUBLIC:PLAINTEXT,INTERN:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLPANE:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL # (default: PLAINTEXT:PLAINTEXT,...) Map between listener names and security protocols. In this scenario this setting is used to define listeners with names.

  kafka-broker2:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-broker2
    networks:
      intern:
        aliases:
          - kafka
    volumes:
      - kafka-broker2:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: broker # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 102 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PUBLIC://0.0.0.0:19092,INTERN://0.0.0.0:9092,REPLICATION://0.0.0.0:9091,CONTROLPANE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PUBLIC://envoy-kafka-broker2:9092,INTERN://kafka-broker2:9092,REPLICATION://kafka-broker2:9091,CONTROLPANE://kafka-broker2:9094 # (required) Describes how the host name that is advertised and can be reached by clients. HOST://localhost:19092 enables access from Docker host.
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLPANE
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # (required in KRaft mode) The listeners used by the controller to define the security protocol.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PUBLIC:PLAINTEXT,INTERN:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLPANE:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL # (default: PLAINTEXT:PLAINTEXT,...) Map between listener names and security protocols. In this scenario this setting is used to define listeners with names.

  kafka-broker3:
    image: ueisele/apache-kafka-server:${KAFKA_VERSION}
    restart: always
    hostname: kafka-broker3
    networks:
      intern:
        aliases:
          - kafka
    volumes:
      - kafka-broker3:/opt/apache/kafka/data
    environment:
      #### Setup ####
      CLUSTER_ID: ${CLUSTER_ID} # In KRaft mode the cluster id must be generated manually. All nodes in a cluster must have the same id.
      AUTO_FORMAT_KAFKA_STORAGE_DIR: "true" # (default: false) In KRaft mode also the storage dir must be formatted manually before the node is started the first time. If set to true, the directory is formatted if it is not formatted until now. However, be careful with this setting, could lead to data loss.
      #### Server Basics ####
      KAFKA_PROCESS_ROLES: broker # (default: "") Defines in which mode the server runs and which roles it has. Valid values are 'broker', 'controller' 'broker,controller' and ''. If empty the server runs in ZooKeeper mode.
      KAFKA_NODE_ID: 103 # (default: -1, required in KRaft mode) The node id for this server.
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller1:9093,2@kafka-controller2:9093,3@kafka-controller3:9093 # (required in KRaft mode) The connect string for the controller quorum
      #### Socket Server Settings ###
      KAFKA_LISTENERS: PUBLIC://0.0.0.0:19092,INTERN://0.0.0.0:9092,REPLICATION://0.0.0.0:9091,CONTROLPANE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PUBLIC://envoy-kafka-broker3:9092,INTERN://kafka-broker3:9092,REPLICATION://kafka-broker3:9091,CONTROLPANE://kafka-broker3:9094 # (required) Describes how the host name that is advertised and can be reached by clients. HOST://localhost:19092 enables access from Docker host.
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_CONTROL_PLANE_LISTENER_NAME: CONTROLPANE
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER # (required in KRaft mode) The listeners used by the controller to define the security protocol.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PUBLIC:PLAINTEXT,INTERN:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLPANE:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL # (default: PLAINTEXT:PLAINTEXT,...) Map between listener names and security protocols. In this scenario this setting is used to define listeners with names.

volumes:
  kafka-controller1:
  kafka-controller2:
  kafka-controller3:
  kafka-broker1:
  kafka-broker2:
  kafka-broker3:

networks:
  public:
    name: ${DOMAIN_PUBLIC}
    driver: bridge
  intern:
    name: ${DOMAIN_INTERN}
    driver: bridge