= KRaft Kafka Cluster and Envoy Proxy

The envoy proxy listens on ports 909[1-3] and forwards to the corresponding Kafka Broker [1-3] to port 19092. The Kafka Brokers are listening on port 19092 and advertises the envoy proxy hostname and their corresponding port (909[1-3]).

----
Client -- 909[1-3] --> Envoy Proxy -- 19092 --> Kafka Broker [1-3]
----

|===
| Envoy Host | Envoy Port | Kafka Broker | Kafka Port | Advertised Listener

| envoy-kafka-broker | 9091 | kafka-broker1 | 19092 | envoy-kafka-broker:9091
| envoy-kafka-broker | 9092 | kafka-broker2 | 19092 | envoy-kafka-broker:9092
| envoy-kafka-broker | 9093 | kafka-broker3 | 19092 | envoy-kafka-broker:9093
|===

NOTE: Using Docker image _ueisele/apache-kafka-server:0.8.0-beta1-8700-g73a54c5_ (3.0.0-SNAPSHOT). It contains a fix which advertises the actual advertised port and not the socket server port (see commit https://github.com/apache/kafka/commit/73a54c5265231b3d764391b70572626a876f1e27 and pull-request https://github.com/apache/kafka/pull/10935). Kafka 2.8.0 returns the socket server port instead of the advertised port and therefore this example does not work with this version.

.Run Envoy, Kafka Controllers and Kafka Brokers
[source,bash]
----
docker-compose up -d
----

.List advertised brokers
[source,bash]
----
docker-compose exec kafkacat kafkacat -b envoy-kafka-broker:9091 -L
----

.Advertised brokers
----
Metadata for all topics (from broker -1: envoy-kafka-broker:9091/bootstrap):
 3 brokers:
  broker 101 at envoy-kafka-broker:9091 (controller)
  broker 102 at envoy-kafka-broker:9092
  broker 103 at envoy-kafka-broker:9093
 0 topics:
----