#!/usr/bin/env bash
set -e
EXAMPLE_DIR="$(readlink -f "$(dirname ${BASH_SOURCE[0]})")"
ROOT="$(readlink -f "${EXAMPLE_DIR}/../..")"

source "${EXAMPLE_DIR}/.env"
source "${ROOT}/examples/generate-ca"
source "${ROOT}/examples/generate-cert"

TARGET_DIR="${EXAMPLE_DIR}/target/certs"
STORE_PASS="changeit"
generateCA
SAN="IP:127.0.0.1,DNS:localhost,DNS:kafka-proxy-l7,DNS:kafka-proxy-l7.${DOMAIN_NAME}" NAME=proxy generateCert
echo $STORE_PASS > "${TARGET_DIR}/store.credentials"