= PoC - L7 Kafka Proxy

https://app.fossa.com/projects/custom%2B33213%2Fgit%40github.com%3Aueisele%2Fkafka-proxy.git?ref=badge_shield[image:https://app.fossa.com/api/projects/custom%2B33213%2Fgit%40github.com%3Aueisele%2Fkafka-proxy.git.svg?type=shield[FOSSA
Status]]

Use Cases for a L7 Proxy:

* Client Metrics
* Advertised Listener Mapping
* Routing (e.g. based on user and tenant, topic, ...)
* Encryption
* Virtual Topics (e.g. with filters)
* Namespaces (multi tenancy)
* Authentication & Authorization
* Policy Enforcement (Topics, Configs, ...)
* Credit-based Quotas (and throttling)

Open topics:

* Passthrough SASL authentication: Make principal available in Kafka proxy
* Filter as plugins
* Transparent request/response forwarding: Do not deserialize if not needed, to support newer Kafka protocols.

== Quick Start

This repository contains example deployments for the Kafka Proxy combined with a Kafka Cluster.
In order to get started just navigate to link:examples/proxyl7-kraft-plaintext/[] and run the following command:

.Start Kafka Cluster and Kafka Proxy
[source,bash]
----
podman up
----

Find additional information at link:examples/proxyl7-kraft-plaintext/README.adoc[].

== Build and Run

.Build the Kafka Proxy
[source,bash]
----
./sbtx clean package packCopyDependencies
----

.Run
[source,bash]
----
./bin/kafka-proxy-start config/proxy.properties
----