#!/usr/bin/env bash
set -e
EXAMPLE_DIR="$(readlink -f "$(dirname ${BASH_SOURCE[0]})")"
ROOT="$(readlink -f "${EXAMPLE_DIR}/../..")"

source "${EXAMPLE_DIR}/.env"
source "${ROOT}/examples/generate-ca"
source "${ROOT}/examples/generate-cert"
source "${ROOT}/examples/btpl"

export TARGET_DIR="${EXAMPLE_DIR}/target"
export GROUP=kafka-proxy
export CA_KEY_PASS="cakeypass"
export CERT_KEY_PASS="certkeypass"
generateCA
NAME=proxy CERT_SAN="IP:127.0.0.1,DNS:localhost,DNS:kafka-proxy-l7" generateCert

btpl "${EXAMPLE_DIR}/client.properties.btpl" "${TARGET_DIR}/client.properties"

if command -v podman &> /dev/null; then
  # if podman is installed, set permissions of generated artifacts to allow access by user appuser if podman is used in rootless mode
  chmod -R ugo=rwX ${TARGET_DIR}
  podman unshare chown -R 1000:1000 ${TARGET_DIR}
fi
