Configuration:
  status: warn
  name: YAMLConfig
  shutdownHook: disable
  thresholdFilter:
    level: trace
  appenders:
    Console:
      name: STDOUT
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d [%p] %c{1} – %m%n"

  Loggers:
    Root:
      level: warn
      AppenderRef:
        ref: STDOUT
    logger:
      - name: net.uweeisele.kafka
        level: info
        additivity: false
        AppenderRef:
          ref: STDOUT
      - name: java.nio
        level: info
        additivity: false
        AppenderRef:
          ref: STDOUT
      - name: org.apache.kafka.common.network.SslTransportLayer
        level: info
        additivity: false
        AppenderRef:
          ref: STDOUT